### ISSUE TITLE
reflecting boundary conditions do not ensure zero mass flux

### ISSUE THREAD

**Issue by BenWibking** [zingale/pyro2#4]
Using reflecting boundary conditions in a (nearly) isothermal exponential atmosphere, I find that pyro does not ensure a zero mass flux at the lower boundary, whether or not I include gravity, _and_ whether or not I reflect the gravity vector at the boundary (it should, of course, be reflected to match the boundary conditions, and I do so by adding a new gravitational acceleration state variable and setting its boundary condition to reflect y-odd).

I have tested this setup in Castro and Athena, which both produce identically zero mass flux at the reflecting boundary.

The initial conditions are prescribed by the following:

```
xmom.d[:,:] = 0.0
ymom.d[:,:] = 0.0
dens.d[:,:] = 0.0
grav.d[:,:] = grav_const # this will be reflected via the boundary conditions routines              

# set the density to be stratified in the y-direction                                               
myg = my_data.grid

p = myg.scratch_array()

dens.d[:,:] = dens1*numpy.exp(-myg.y2d/scale_height)
p.d[:,:] = dens.d*cs*cs/gamma

# set the energy (P = cs2*dens)                                                                     
ener.d[:,:] = p.d[:,:]/(gamma - 1.0) + \
    0.5*(xmom.d[:,:]**2 + ymom.d[:,:]**2)/dens.d[:,:]
```

**Comment by BenWibking** [comment]
I compute the mass flux (unnormalized) as follows:

        # compute flux at lower boundary                                                                
        print("(before) grav:",grav.d[4,:myg.jlo+1]) # let's check that reflection is working.          
        print("mass fluxes:",np.sum(Flux_y.v(n=self.vars.idens)[:,myg.jlo])) # fluxes are stored on lef\
t edge, per unsplitFluxes.py, so this is the flux into the grid along the lower boundary

**Comment by BenWibking** [comment]
My fork is here: https://github.com/BenWibking/pyro2-1
Running ./failure_mode.sh should reproduce this problem.

**Comment by zingale** [comment]
you're right, I don't reflect the gravity in the compressible solver -- I'll fix that.  The lm_atm solver does reflect it.  This is just an oversight.

As for the hard-zero flux at the boundary, Castro specifically resets the flux at the interface to be zero across symmetry planes, I suppose I can do the same.  I think that just numerical precision can cause it to be slightly non-zero (or some ifs somewhere along the way to are not properly done symmetrically).

**Comment by BenWibking** [comment]
I tried setting the mass flux to zero 'by hand' but that seemed to produce invalid states and NaN proliferate rather quickly.  I tried to set the floors before the boundary conditions are set, which seemed to help, but not quite fix the problem entirely.

**Comment by BenWibking** [comment]
Now that I run this again, I see that I am getting different failures seemingly randomly on each run (with the same initial conditions).  Is this indicate something wrong with my fortran compiler? On some runs I see:

```
/home/payne/wibking.1/pyro_dev/pyro2/compressible/unsplitFluxes.py:280: RuntimeWarning: overflow encountered in square
  0.5*V_r[:,:,vars.irho]*(V_r[:,:,vars.iu]**2 + V_r[:,:,vars.iv]**2)
```

and on others I see

```
/home/payne/wibking.1/pyro_dev/pyro2/compressible/unsplitFluxes.py:440: RuntimeWarning: invalid value encountered in subtract
  - 0.5*dtdx*(F_x.ip(1, buf=b, n=n) - F_x.v(buf=b, n=n))
```

**Comment by zingale** [comment]
I just pushed a fix for the gravitational source terms.

I'll do the flux after I teach.  Not sure what the errors you are seeing -- did you make sure to recompile the auxillary libraries (using mk.sh)?

**Comment by BenWibking** [comment]
Yes, I ran ./mk.sh clean and then ./mk.sh. What do you get when you run
the code from my fork?

On 11/23/2015 03:26 PM, Michael Zingale wrote:
> I just pushed a fix for the gravitational source terms.
> 
> I'll do the flux after I teach. Not sure what the errors you are seeing
> -- did you make sure to recompile the auxillary libraries (using mk.sh)?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zingale/pyro2/issues/4#issuecomment-159054072>.
> 

-- 
Ben Wibking
Dept. of Astronomy
The Ohio State University

**Comment by zingale** [comment]
I just implemented the Riemann fix for the CGF Riemann solver at solid boundaries.  I didn't do HLLC (yet).  Give that a try.

**Comment by BenWibking** [comment]
Still not working for me. No more random crashes (maybe my fault) but still leaking mass.

**Comment by zingale** [comment]
make sure you are not using the HLLC solver -- I didn't implement the boundary bit in that one.  Set

riemann = CGF

**Comment by BenWibking** [comment]
Ah, my mistake. So far it looks like it's conserving mass perfectly. Thanks.

**Comment by BenWibking** [comment]
Hmm, except now my timesteps are becoming very very small and not much seems to be happening, at least when I include reflecting boundaries on the upper y-boundary as well. Any idea what is going on now?

**Comment by BenWibking** [comment]
This seems not to support an exponential atmosphere above it. The atmosphere just collapses onto the lower boundary as if it had no pressure support.  It looks like this:
![iso_0000 pyro](https://cloud.githubusercontent.com/assets/1781919/11374439/113df14c-92a4-11e5-9921-6247ba6dcd96.png)
![iso_0015 pyro](https://cloud.githubusercontent.com/assets/1781919/11374442/15a0f8ce-92a4-11e5-9dcf-c002c19f9730.png)

**Comment by zingale** [comment]
take a look at the compressible problem "bubble" (you'll have to do a git
pull).  That supports a hydrostatic atmosphere.

On Tue, Nov 24, 2015 at 12:08 PM, Ben Wibking <notifications@github.com>
wrote:

> This seems not to support an exponential atmosphere above it. The
> atmosphere just collapses onto the lower boundary as if it had no pressure
> support. It looks like this:
> [image: iso_0000 pyro]
> <https://cloud.githubusercontent.com/assets/1781919/11374439/113df14c-92a4-11e5-9921-6247ba6dcd96.png>
> [image: iso_0015 pyro]
> <https://cloud.githubusercontent.com/assets/1781919/11374442/15a0f8ce-92a4-11e5-9dcf-c002c19f9730.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zingale/pyro2/issues/4#issuecomment-159341886>.
>



-- 
Michael Zingale
Associate Professor

Dept. of Physics & Astronomy • Stony Brook University • Stony Brook, NY
11794-3800
*phone*:  631-632-8225
*e-mail*: Michael.Zingale@stonybrook.edu
*web*: http://www.astro.sunysb.edu/mzingale
github: http://github.com/zingale

**Comment by BenWibking** [comment]
Ah, ok. Good, it works. (It turns out I had introduced a typo when merging...)

The only thing that I am confused about now is how to directly measure the mass flux - when I do
`np.sum(Flux_y.v(n=self.vars.idens)[myg.ilo:myg.ihi+1,myg.jlo])*dtdy` I still get nonzero values... I assume I am misunderstanding the array indexing?

**Comment by zingale** [comment]
that must be coming then from the artificial viscosity.  Try setting
cvisc=0.0.

On Tue, Nov 24, 2015 at 1:50 PM, Ben Wibking <notifications@github.com>
wrote:

> Ah, ok. Good, it works. (It turns out I had introduced a typo when
> merging...)
>
> The only thing that I am confused about now is how to directly measure the
> mass flux - when I do
> np.sum(Flux_y.v(n=self.vars.idens)[myg.ilo:myg.ihi+1,myg.jlo])*dtdy I
> still get nonzero values... I assume I am misunderstanding the array
> indexing?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zingale/pyro2/issues/4#issuecomment-159370065>.
>



-- 
Michael Zingale
Associate Professor

Dept. of Physics & Astronomy • Stony Brook University • Stony Brook, NY
11794-3800
*phone*:  631-632-8225
*e-mail*: Michael.Zingale@stonybrook.edu
*web*: http://www.astro.sunysb.edu/mzingale
github: http://github.com/zingale

**Comment by BenWibking** [comment]
I have already set cvisc=0.0.  (I also disabled shock flattening, though
naively I would not expect that to change anything.)

On 11/24/2015 02:35 PM, Michael Zingale wrote:
> that must be coming then from the artificial viscosity. Try setting
> cvisc=0.0.
> 
> On Tue, Nov 24, 2015 at 1:50 PM, Ben Wibking <notifications@github.com>
> wrote:
> 
>> Ah, ok. Good, it works. (It turns out I had introduced a typo when
>> merging...)
>>
>> The only thing that I am confused about now is how to directly measure the
>> mass flux - when I do
>> np.sum(Flux_y.v(n=self.vars.idens)[myg.ilo:myg.ihi+1,myg.jlo])*dtdy I
>> still get nonzero values... I assume I am misunderstanding the array
>> indexing?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/zingale/pyro2/issues/4#issuecomment-159370065>.
>>
> 
> 
> 
> -- 
> Michael Zingale
> Associate Professor
> 
> Dept. of Physics & Astronomy • Stony Brook University • Stony Brook, NY
> 11794-3800
> *phone*: 631-632-8225
> *e-mail*: Michael.Zingale@stonybrook.edu
> *web*: http://www.astro.sunysb.edu/mzingale
> github: http://github.com/zingale
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zingale/pyro2/issues/4#issuecomment-159382342>.
> 

-- 
Ben Wibking
Dept. of Astronomy
The Ohio State University

**Comment by zingale** [comment]
this issue is a few years old -- is this still a problem?

**Comment by BenWibking** [comment]
I've switched to Athena for some time now, so I don't know whether or
not it's an issue with the current version.
